"""
Approval Gate

Classifies each proposed fix as:
  AUTO_MERGE — safe to commit directly (low blast radius, reversible)
  HUMAN_REQUIRED — must be reviewed by a human before applying

Auto-merge criteria (ALL must hold):
  - Fix touches no sensitive areas (auth, payment, migrations, secrets, public API)
  - Patch is small (< 30 lines changed)
  - All existing tests still pass after the patch
  - The fix was verified by the Verification Agent

Anything not satisfying ALL criteria → HUMAN_REQUIRED.

Then separates fixes into auto_applied_fixes and pending_human_fixes lists
and writes a human-readable PR comment body for the Orchestrator to post.
"""

from __future__ import annotations

from src.core.config import settings
from src.core.logging import get_logger
from src.core.state import (
    FixClassification,
    FindingSeverity,
    PipelineState,
    ProposedFix,
    RiskLevel,
)

log = get_logger(__name__)

_SENSITIVE_KEYWORDS = set(settings.sensitive_patterns)
_MAX_AUTO_PATCH_LINES = 30


def _is_auto_mergeable(fix: ProposedFix, state: PipelineState) -> bool:
    if not fix.patch.strip():
        return False

    # Sensitive file check
    for fpath in fix.affected_files:
        low = fpath.lower()
        if any(kw in low for kw in _SENSITIVE_KEYWORDS):
            return False

    # Patch size check
    changed_lines = sum(
        1 for line in fix.patch.splitlines() if line.startswith(("+", "-"))
        and not line.startswith(("+++", "---"))
    )
    if changed_lines > _MAX_AUTO_PATCH_LINES:
        return False

    # High-risk PR with CRITICAL findings → force human review on all fixes
    critical_count = sum(
        1 for f in state.all_findings() if f.severity == FindingSeverity.CRITICAL
    )
    if state.risk and state.risk.level == RiskLevel.HIGH and critical_count > 0:
        return False

    return True


def _build_pr_comment(state: PipelineState) -> str:
    lines: list[str] = ["## SENTINEL Review Report\n"]

    # Risk badge
    risk = state.risk
    if risk:
        emoji = {"low": "🟢", "medium": "🟡", "high": "🔴"}.get(risk.level.value, "⚪")
        lines.append(f"**Risk Level:** {emoji} {risk.level.value.upper()} (score: {risk.score:.2f})\n")
        if risk.reasons:
            lines.append("**Risk reasons:** " + "; ".join(risk.reasons[:3]) + "\n")

    # Review findings
    findings = state.consolidated_findings
    if findings:
        lines.append(f"\n### Code Review ({len(findings)} findings)\n")
        by_sev = {}
        for f in findings:
            by_sev.setdefault(f.severity, []).append(f)
        for sev in [FindingSeverity.CRITICAL, FindingSeverity.HIGH, FindingSeverity.MEDIUM, FindingSeverity.LOW, FindingSeverity.INFO]:
            group = by_sev.get(sev, [])
            if not group:
                continue
            lines.append(f"\n**{sev.value.upper()}** ({len(group)})\n")
            for finding in group[:5]:  # cap display at 5 per severity
                loc = f"`{finding.file_path}`"
                if finding.line_start:
                    loc += f" line {finding.line_start}"
                lines.append(f"- **{finding.title}** — {loc}")
                if finding.rationale:
                    lines.append(f"  > {finding.rationale}")
                if finding.suggestion:
                    lines.append(f"  *Suggestion:* {finding.suggestion}")
    else:
        lines.append("\n### Code Review\n✅ No significant findings.\n")

    # Test coverage
    results = state.test_results
    if results:
        total_passed = sum(r.passed for r in results)
        total_failed = sum(r.failed + r.errors for r in results)
        lines.append(f"\n### Tests\n")
        lines.append(f"- Passed: {total_passed}  Failed: {total_failed}")
        if state.coverage_gaps:
            lines.append(f"- Coverage gaps: {len(state.coverage_gaps)}")
            for gap in state.coverage_gaps[:3]:
                lines.append(f"  - {gap}")

    # Auto-applied fixes
    if state.auto_applied_fixes:
        lines.append(f"\n### Auto-Applied Fixes ({len(state.auto_applied_fixes)})\n")
        for fix in state.auto_applied_fixes:
            lines.append(f"- ✅ {fix.description}")
            if fix.commit_sha:
                lines.append(f"  Commit: `{fix.commit_sha[:8]}`")
            if fix.rationale:
                lines.append(f"  > {fix.rationale}")

    # Pending human fixes
    if state.pending_human_fixes:
        lines.append(f"\n### Pending Human Review ({len(state.pending_human_fixes)})\n")
        for fix in state.pending_human_fixes:
            lines.append(f"- ⏳ {fix.description}")
            if fix.rationale:
                lines.append(f"  > {fix.rationale}")
            lines.append(f"  *Affected:* {', '.join(fix.affected_files[:3])}")

    lines.append("\n---\n*Generated by [SENTINEL](https://github.com/SENTINEL)*")
    return "\n".join(lines)


def run(state: PipelineState) -> dict:
    log.info("approval_gate_start", fixes=len(state.proposed_fixes))

    auto_fixes: list[ProposedFix] = []
    human_fixes: list[ProposedFix] = []

    for fix in state.proposed_fixes:
        if _is_auto_mergeable(fix, state):
            classified = fix.model_copy(update={"classification": FixClassification.AUTO_MERGE})
            auto_fixes.append(classified)
            log.info("fix_auto_merge", description=fix.description[:60])
        else:
            classified = fix.model_copy(update={"classification": FixClassification.HUMAN_REQUIRED})
            human_fixes.append(classified)
            log.info("fix_human_required", description=fix.description[:60])

    pr_comment = _build_pr_comment(
        state.model_copy(update={
            "auto_applied_fixes": auto_fixes,
            "pending_human_fixes": human_fixes,
        })
    )

    log.info(
        "approval_gate_done",
        auto=len(auto_fixes),
        human=len(human_fixes),
    )
    return {
        "auto_applied_fixes": auto_fixes,
        "pending_human_fixes": human_fixes,
        "pr_comment": pr_comment,
    }
