"""
SENTINEL entry point

Usage (after pip install sentinel-ai):
  sentinel init                              # first-time setup — saves API keys
  sentinel scan --path ./my-project --all   # scan a local project
  sentinel scan --path . --staged           # staged changes only
  sentinel scan --path . --branch main      # diff vs a branch
  sentinel run --repo owner/repo --pr 42    # run on a GitHub PR
  sentinel serve                             # start the webhook server
  sentinel maintain                          # run KB maintenance manually
"""

from __future__ import annotations

import argparse
import sys

# Ensure UTF-8 output on Windows (required for Rich Unicode characters)
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except AttributeError:
        pass


def cmd_init(args: argparse.Namespace) -> None:
    """Interactive first-time setup — saves API keys to ~/.sentinel/.env"""
    from pathlib import Path
    from rich.console import Console
    from rich.prompt import Prompt
    from rich.panel import Panel

    c = Console()
    c.print()
    c.print(Panel.fit(
        "[bold cyan]Welcome to SENTINEL[/bold cyan]\n"
        "[dim]Self-healing AI code quality pipeline[/dim]\n\n"
        "Let's get you set up in 2 minutes.\n"
        "Both keys below are [bold]completely free[/bold] — no credit card needed.",
        border_style="cyan",
    ))
    c.print()

    # ── Groq ──────────────────────────────────────────────────────────────────
    c.print("[bold]Step 1 of 2 — Groq API key[/bold] [dim](fast inference, free)[/dim]")
    c.print("  → Get yours at: [cyan]https://console.groq.com[/cyan]")
    c.print("  → Click [bold]API Keys[/bold] → [bold]Create API Key[/bold]")
    c.print()
    groq_key = Prompt.ask("  Paste your Groq key [dim](starts with gsk_)[/dim]").strip()
    c.print()

    # ── HuggingFace ───────────────────────────────────────────────────────────
    c.print("[bold]Step 2 of 2 — HuggingFace token[/bold] [dim](fallback when Groq quota runs out)[/dim]")
    c.print("  → Get yours at: [cyan]https://huggingface.co/settings/tokens[/cyan]")
    c.print("  → Click [bold]New token[/bold] → choose [bold]Read[/bold] → Create")
    c.print()
    hf_key = Prompt.ask("  Paste your HuggingFace token [dim](starts with hf_)[/dim]").strip()
    c.print()

    # ── Save to ~/.sentinel/.env ───────────────────────────────────────────────
    sentinel_dir = Path.home() / ".sentinel"
    sentinel_dir.mkdir(exist_ok=True)
    env_file = sentinel_dir / ".env"

    env_content = f"""# SENTINEL global config — generated by `sentinel init`
# Edit this file to change settings.
LLM_PROVIDER=cascade
GROQ_API_KEY={groq_key}
HUGGINGFACE_API_KEY={hf_key}
GROQ_MODEL_STRONG=llama-3.3-70b-versatile
GROQ_MODEL_FAST=llama-3.1-8b-instant
HF_MODEL_STRONG=Qwen/Qwen2.5-72B-Instruct
HF_MODEL_FAST=Qwen/Qwen2.5-7B-Instruct
CHROMA_PERSIST_DIR={sentinel_dir / "chroma"}
LOG_FILE={sentinel_dir / "sentinel.log"}
SANDBOX_IMAGE=sentinel-sandbox:latest
SANDBOX_TIMEOUT_SECONDS=120
SANDBOX_MEMORY_LIMIT=512m
SANDBOX_CPU_PERIOD=100000
SANDBOX_CPU_QUOTA=50000
"""
    env_file.write_text(env_content, encoding="utf-8")

    # ── Check Docker ──────────────────────────────────────────────────────────
    import subprocess
    docker_ok = subprocess.run(["docker", "info"], capture_output=True).returncode == 0

    c.print(f"[green]Config saved →[/green] [cyan]{env_file}[/cyan]")
    c.print()

    if not docker_ok:
        c.print("[yellow]Warning:[/yellow] Docker is not running.")
        c.print("  SENTINEL needs Docker for its sandbox. Install it at: [cyan]https://docker.com[/cyan]")
        c.print()

    c.print("[bold green]SENTINEL is ready![/bold green]")
    c.print()
    c.print("Run your first scan:")
    c.print("  [bold cyan]sentinel scan --path ./your-project --all[/bold cyan]")
    c.print()


def cmd_github_setup(args: argparse.Namespace) -> None:
    """Interactive wizard to create a GitHub App and configure the webhook."""
    import secrets
    from pathlib import Path
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Confirm, Prompt
    from rich.rule import Rule

    c = Console()
    c.print()
    c.print(Panel.fit(
        "[bold cyan]SENTINEL — GitHub App Setup[/bold cyan]\n"
        "[dim]This wizard creates a GitHub App so SENTINEL can review your PRs automatically.[/dim]\n\n"
        "Estimated time: [bold]3 minutes[/bold]",
        border_style="cyan",
    ))
    c.print()

    # ── Step 1: Webhook secret ────────────────────────────────────────────────
    c.print(Rule("[bold]Step 1 of 4[/bold] — Generate webhook secret", style="cyan"))
    webhook_secret = secrets.token_hex(32)
    c.print(f"\n  Generated secret: [bold yellow]{webhook_secret}[/bold yellow]")
    c.print("  [dim]Copy this — you'll paste it into GitHub in the next step.[/dim]\n")

    # ── Step 2: ngrok tunnel (local dev) ─────────────────────────────────────
    c.print(Rule("[bold]Step 2 of 4[/bold] — Tunnel URL (local dev)", style="cyan"))
    c.print("\n  GitHub needs a public HTTPS URL to send webhooks to.")
    c.print("  For [bold]local development[/bold], we can start an ngrok tunnel for you.")
    c.print("  For [bold]production[/bold], you'll use your server's public URL instead.\n")

    public_url: str = ""
    use_ngrok = Confirm.ask("  Start an ngrok tunnel now for local dev?", default=True)
    if use_ngrok:
        try:
            from pyngrok import ngrok as _ngrok
            port = args.port if hasattr(args, "port") else 8000
            tunnel = _ngrok.connect(port, "http")
            public_url = tunnel.public_url.replace("http://", "https://")
            c.print(f"\n  [green]Tunnel started:[/green] [cyan]{public_url}[/cyan]")
            c.print(f"  Webhook URL:   [bold]{public_url}/webhook/github[/bold]\n")
        except ImportError:
            c.print("\n  [yellow]pyngrok not installed.[/yellow] Install it with:")
            c.print("    [bold]pip install pyngrok[/bold]\n")
            public_url = Prompt.ask("  Enter your public server URL", default="https://your-server.com").rstrip("/")
            c.print()
        except Exception as exc:
            c.print(f"\n  [yellow]ngrok failed:[/yellow] {exc}")
            public_url = Prompt.ask("  Enter your public server URL", default="https://your-server.com").rstrip("/")
            c.print()
    else:
        public_url = Prompt.ask("  Enter your public server URL", default="https://your-server.com").rstrip("/")
        c.print()

    webhook_url = f"{public_url}/webhook/github"

    # ── Step 3: Create GitHub App ─────────────────────────────────────────────
    c.print(Rule("[bold]Step 3 of 4[/bold] — Create GitHub App", style="cyan"))
    c.print()
    c.print("  Open this URL in your browser:")
    c.print("    [bold cyan]https://github.com/settings/apps/new[/bold cyan]\n")
    c.print("  Fill in the form as follows:\n")
    c.print("  [bold]GitHub App name:[/bold]  SENTINEL (or any name you like)")
    c.print("  [bold]Homepage URL:[/bold]     https://github.com/ZenDev-arc/sentinel")
    c.print(f"  [bold]Webhook URL:[/bold]     [cyan]{webhook_url}[/cyan]")
    c.print(f"  [bold]Webhook secret:[/bold]  [yellow]{webhook_secret}[/yellow]")
    c.print()
    c.print("  [bold]Permissions → Repository permissions:[/bold]")
    c.print("    Pull requests  → [green]Read & Write[/green]")
    c.print("    Contents       → [green]Read & Write[/green]  (for auto-committing fixes)")
    c.print("    Metadata       → [green]Read-only[/green]   (mandatory)")
    c.print()
    c.print("  [bold]Subscribe to events:[/bold]")
    c.print("    [green]✓[/green] Pull request")
    c.print("    [green]✓[/green] Push  [dim](optional — enables revert detection)[/dim]")
    c.print()
    c.print("  [bold]Where can this app be installed?[/bold]")
    c.print("    → Only on this account  [dim](recommended for personal use)[/dim]")
    c.print("    → Any account           [dim](if you want to share it)[/dim]")
    c.print()
    c.print("  Click [bold]Create GitHub App[/bold].")
    c.print()
    Prompt.ask("  Press [bold]Enter[/bold] once you've created the app")
    c.print()

    # ── Step 4: Collect App credentials ──────────────────────────────────────
    c.print(Rule("[bold]Step 4 of 4[/bold] — Save credentials", style="cyan"))
    c.print()
    c.print("  After creating the app, GitHub shows the App settings page.")
    c.print("  Copy the [bold]App ID[/bold] from the top of the page.\n")
    app_id = Prompt.ask("  GitHub App ID").strip()

    c.print()
    c.print("  Scroll down on the App settings page to [bold]Private keys[/bold].")
    c.print("  Click [bold]Generate a private key[/bold] — a .pem file will download.\n")
    default_pem = str(Path.home() / ".sentinel" / "github-app.pem")
    pem_path = Prompt.ask(
        f"  Path to the downloaded .pem file",
        default=default_pem,
    ).strip()
    pem_path = str(Path(pem_path).expanduser().resolve())

    c.print()
    c.print("  [bold]Install the App on your repository:[/bold]")
    c.print("    → On the App page click [bold]Install App[/bold] (left sidebar)")
    c.print("    → Select your account / organisation → install on the repo(s) you want reviewed")
    c.print()
    Prompt.ask("  Press [bold]Enter[/bold] once you've installed the app")

    # ── Save to ~/.sentinel/.env ───────────────────────────────────────────────
    sentinel_dir = Path.home() / ".sentinel"
    sentinel_dir.mkdir(exist_ok=True)
    env_file = sentinel_dir / ".env"

    # Read existing content and update/append GitHub keys
    existing = env_file.read_text(encoding="utf-8") if env_file.exists() else ""

    def _set_key(content: str, key: str, value: str) -> str:
        import re
        if re.search(rf"^{key}\s*=", content, re.MULTILINE):
            return re.sub(rf"^{key}\s*=.*$", f"{key}={value}", content, flags=re.MULTILINE)
        return content + f"\n{key}={value}"

    existing = _set_key(existing, "GITHUB_APP_ID", app_id)
    existing = _set_key(existing, "GITHUB_WEBHOOK_SECRET", webhook_secret)
    existing = _set_key(existing, "GITHUB_APP_PRIVATE_KEY_PATH", pem_path)

    env_file.write_text(existing, encoding="utf-8")

    c.print()
    c.print(f"[green]GitHub credentials saved →[/green] [cyan]{env_file}[/cyan]")
    c.print()
    c.print("[bold green]Done![/bold green]  Start the webhook server with:")
    c.print("  [bold cyan]sentinel serve[/bold cyan]")
    if use_ngrok:
        c.print()
        c.print(f"  [dim]ngrok tunnel:[/dim] [cyan]{public_url}[/cyan]")
        c.print("  [dim]Keep this terminal open — the tunnel closes when you exit.[/dim]")
    c.print()


def cmd_serve(args: argparse.Namespace) -> None:
    import uvicorn

    from rich.console import Console
    from src.api.webhook import app
    from src.core.config import settings
    from src.core.logging import configure_logging, get_logger
    from src.scheduler.maintenance import start_scheduler

    configure_logging()
    log = get_logger(__name__)
    c = Console()

    # ── Validate GitHub is configured ─────────────────────────────────────────
    has_github_app = bool(settings.GITHUB_APP_ID and settings.github_app_private_key)
    has_pat = bool(settings.GITHUB_TOKEN)
    has_webhook_secret = bool(settings.GITHUB_WEBHOOK_SECRET)

    c.print()
    c.print("[bold cyan]SENTINEL[/bold cyan]  webhook server")
    c.print()

    if not has_webhook_secret:
        c.print("[yellow]Warning:[/yellow] GITHUB_WEBHOOK_SECRET is not set.")
        c.print("  All incoming webhooks will be rejected.")
        c.print("  Run [bold]sentinel github-setup[/bold] to configure.\n")

    if not has_github_app and not has_pat:
        c.print("[yellow]Warning:[/yellow] No GitHub authentication configured.")
        c.print("  SENTINEL can receive webhooks but cannot post comments or commit fixes.")
        c.print("  Set GITHUB_TOKEN (simple) or run [bold]sentinel github-setup[/bold] (full App).\n")

    auth_mode = "GitHub App" if has_github_app else ("PAT" if has_pat else "none")
    c.print(f"  Auth mode      : [cyan]{auth_mode}[/cyan]")
    c.print(f"  Webhook secret : [cyan]{'configured' if has_webhook_secret else 'MISSING'}[/cyan]")
    c.print(f"  Listening on   : [cyan]http://{args.host}:{args.port}[/cyan]")
    c.print(f"  Webhook URL    : [cyan]http://{args.host}:{args.port}/webhook/github[/cyan]")
    c.print()
    c.print("  [dim]For local dev, expose this port with:[/dim]")
    c.print("  [dim]  ngrok http {port}[/dim]".replace("{port}", str(args.port)))
    c.print()

    start_scheduler(repo_root=args.repo_root)
    uvicorn.run(
        app,
        host=args.host,
        port=args.port,
        log_config=None,
    )


def cmd_run(args: argparse.Namespace) -> None:
    from src.core.logging import configure_logging
    from src.core.pipeline import compile_pipeline
    from src.core.state import PRMetadata, PipelineState
    from src.integrations.git_utils import fetch_pr_diff, fetch_pr_files
    from src.integrations.github_client import GitHubClient

    configure_logging(quiet=True)

    gh = GitHubClient()
    diff = fetch_pr_diff(args.repo, args.pr)
    files = fetch_pr_files(args.repo, args.pr)
    pr_meta = gh.fetch_pr_metadata(args.repo, args.pr)
    pr_meta = pr_meta.model_copy(update={"diff": diff, "files_changed": files})

    initial_state = PipelineState(pr=pr_meta, force_review=getattr(args, "force_review", False))
    pipeline = compile_pipeline()

    from rich.console import Console
    Console().print(f"\n[bold cyan]SENTINEL[/bold cyan]  [cyan]{args.repo}#{args.pr}[/cyan]\n")
    _run_and_display(pipeline, initial_state, report_title="SENTINEL PR REPORT")


def cmd_scan(args: argparse.Namespace) -> None:
    """Run SENTINEL on local code — no GitHub PR required."""
    import re
    import subprocess
    import tarfile
    from io import BytesIO
    from pathlib import Path

    from src.core.logging import configure_logging
    from src.core.pipeline import compile_pipeline
    from src.core.state import PRMetadata, PipelineState

    configure_logging(quiet=True)

    scan_path = Path(args.path).resolve()
    if not scan_path.exists():
        print(f"Error: path '{scan_path}' does not exist.")
        sys.exit(1)

    _SKIP = (".git", "__pycache__", ".egg-info", "node_modules", ".venv", "venv", "dist", "build", ".next", "coverage", ".turbo")
    _SOURCE_EXTS = (".py", ".js", ".ts", ".jsx", ".tsx", ".mjs", ".cjs")

    def _collect_source_files(root: "Path") -> "tuple[list[str], str, int]":
        src_files: list[str] = []
        full_diff = ""
        added = 0
        for p in sorted(root.rglob("*")):
            if not p.is_file() or p.suffix not in _SOURCE_EXTS:
                continue
            rel = str(p.relative_to(root)).replace("\\", "/")
            if any(s in rel for s in _SKIP):
                continue
            src_files.append(rel)
            try:
                content = p.read_text(encoding="utf-8", errors="replace")
                lines = content.splitlines()
                added += len(lines)
                full_diff += f"\n--- /dev/null\n+++ b/{rel}\n@@ -0,0 +1,{len(lines)} @@\n"
                full_diff += "\n".join(f"+{l}" for l in lines) + "\n"
            except Exception:
                pass
        return src_files, full_diff, added

    diff = ""
    files_changed: list[str] = []
    additions = deletions = 0

    if args.all:
        print("--all flag set — scanning every source file in the path.")
        files_changed, diff, additions = _collect_source_files(scan_path)
    elif args.staged:
        diff_cmd = ["git", "diff", "--cached"]
        result = subprocess.run(diff_cmd, capture_output=True, text=True, cwd=str(scan_path), encoding="utf-8", errors="replace")
        diff = result.stdout
    elif args.branch:
        diff_cmd = ["git", "diff", args.branch]
        result = subprocess.run(diff_cmd, capture_output=True, text=True, cwd=str(scan_path), encoding="utf-8", errors="replace")
        diff = result.stdout
    else:
        result = subprocess.run(["git", "diff", "HEAD"], capture_output=True, text=True, cwd=str(scan_path), encoding="utf-8", errors="replace")
        diff = result.stdout
        if not diff.strip():
            result = subprocess.run(["git", "diff", "HEAD~1", "HEAD"], capture_output=True, text=True, cwd=str(scan_path), encoding="utf-8", errors="replace")
            diff = result.stdout

    if not args.all:
        for line in diff.splitlines():
            if line.startswith("+++ b/"):
                fp = line[6:]
                if fp and fp not in files_changed:
                    files_changed.append(fp)
            elif line.startswith("+") and not line.startswith("+++"):
                additions += 1
            elif line.startswith("-") and not line.startswith("---"):
                deletions += 1

        if not files_changed:
            print("No git diff found — falling back to full source file scan.")
            files_changed, diff, additions = _collect_source_files(scan_path)

    if not files_changed:
        print("Nothing to scan — no source files found and no git diff.")
        sys.exit(0)

    remote = subprocess.run(
        ["git", "remote", "get-url", "origin"],
        capture_output=True, text=True, cwd=str(scan_path),
    )
    repo_name = "local/scan"
    if remote.returncode == 0:
        m = re.search(r"[:/]([^/]+/[^/]+?)(?:\.git)?$", remote.stdout.strip())
        if m:
            repo_name = m.group(1)

    print(f"Packaging {scan_path.name} for sandbox…")
    buf = BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for p in sorted(scan_path.rglob("*")):
            rel = str(p.relative_to(scan_path)).replace("\\", "/")
            if any(s in rel for s in _SKIP):
                continue
            if p.is_file():
                try:
                    tar.add(str(p), arcname=rel)
                except Exception:
                    pass
    repo_archive = buf.getvalue()

    pr_meta = PRMetadata(
        repo_full_name=repo_name,
        pr_number=0,
        pr_title=f"Local scan: {scan_path.name}",
        pr_body="",
        base_branch="main",
        head_branch="local",
        head_sha="local",
        author="local",
        files_changed=files_changed,
        diff=diff,
        additions=additions,
        deletions=deletions,
    )

    initial_state = PipelineState(pr=pr_meta, repo_archive=repo_archive, force_review=getattr(args, "force_review", False))
    pipeline = compile_pipeline()

    from rich.console import Console
    from rich.table import Table
    from rich import box as rbox
    c = Console()
    c.print()
    c.print(f"[bold cyan]SENTINEL[/bold cyan]  local scan")
    info = Table.grid(padding=(0, 3))
    info.add_column(style="dim")
    info.add_column(style="cyan")
    info.add_row("Path",  str(scan_path))
    info.add_row("Repo",  repo_name)
    info.add_row("Files", str(len(files_changed)))
    info.add_row("Lines", f"+{additions}  -{deletions}")
    c.print(info)
    c.print()

    from src.cli.display import print_report, run_with_progress
    final_state = run_with_progress(pipeline, initial_state)
    print_report(final_state, title="SENTINEL LOCAL SCAN REPORT")

    if args.output:
        from pathlib import Path as _P
        _P(args.output).write_text(final_state.pr_comment or "No findings.", encoding="utf-8")
        c.print(f"[dim]Report saved →[/dim] [cyan]{args.output}[/cyan]")


def _run_and_display(pipeline, initial_state, report_title: str) -> None:
    from src.cli.display import print_report, run_with_progress
    final_state = run_with_progress(pipeline, initial_state)
    print_report(final_state, title=report_title)


def cmd_maintain(args: argparse.Namespace) -> None:
    from src.agents.self_healing import consolidation, consistency, curator, drift_checker
    from src.core.logging import configure_logging
    from src.knowledge_base.store import KnowledgeBaseStore

    configure_logging()
    kb = KnowledgeBaseStore()
    print("Running KB maintenance…")
    print("Curator:      ", curator.run(kb))
    print("Drift-Checker:", drift_checker.run(kb, args.repo_root))
    print("Consistency:  ", consistency.run(kb))
    print("Consolidation:", consolidation.run(kb))


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="sentinel",
        description="SENTINEL — self-healing AI code quality pipeline",
    )
    sub = parser.add_subparsers(dest="command")

    # init
    p_init = sub.add_parser("init", help="First-time setup — configure API keys")
    p_init.set_defaults(func=cmd_init)

    # github-setup
    p_github = sub.add_parser("github-setup", help="Interactive wizard to connect a GitHub App")
    p_github.add_argument("--port", type=int, default=8000, help="Port the server will listen on")
    p_github.set_defaults(func=cmd_github_setup)

    # serve
    p_serve = sub.add_parser("serve", help="Start the webhook server")
    p_serve.add_argument("--host", default="0.0.0.0")
    p_serve.add_argument("--port", type=int, default=8000)
    p_serve.add_argument("--repo-root", default=".", help="Local path to the monitored repo")
    p_serve.set_defaults(func=cmd_serve)

    # run
    p_run = sub.add_parser("run", help="Run pipeline manually on a GitHub PR")
    p_run.add_argument("--repo", required=True, help="owner/repo")
    p_run.add_argument("--pr", type=int, required=True, help="PR number")
    p_run.add_argument("--force-review", action="store_true", dest="force_review")
    p_run.set_defaults(func=cmd_run)

    # scan
    p_scan = sub.add_parser("scan", help="Scan local code — no GitHub PR required")
    p_scan.add_argument("--path", default=".", help="Directory to scan (default: current dir)")
    p_scan.add_argument("--all", action="store_true", help="Scan every source file (ignores git diff)")
    p_scan.add_argument("--staged", action="store_true", help="Scan only staged git changes")
    p_scan.add_argument("--branch", default=None, help="Diff against this branch (e.g. main)")
    p_scan.add_argument("--force-review", action="store_true", dest="force_review")
    p_scan.add_argument("--output", default=None, help="Save report to file (e.g. report.md)")
    p_scan.set_defaults(func=cmd_scan)

    # maintain
    p_maintain = sub.add_parser("maintain", help="Run KB maintenance agents manually")
    p_maintain.add_argument("--repo-root", default=".", help="Local path to the monitored repo")
    p_maintain.set_defaults(func=cmd_maintain)

    args = parser.parse_args()
    if not hasattr(args, "func"):
        parser.print_help()
        sys.exit(1)
    args.func(args)


if __name__ == "__main__":
    main()
