"""
SENTINEL entry point

Usage (after pip install sentinel-ai):
  sentinel init                              # first-time setup — saves API keys
  sentinel scan --path ./my-project --all   # scan a local project
  sentinel scan --path . --staged           # staged changes only
  sentinel scan --path . --branch main      # diff vs a branch
  sentinel run --repo owner/repo --pr 42    # run on a GitHub PR
  sentinel serve                             # start the webhook server
  sentinel maintain                          # run KB maintenance manually
"""

from __future__ import annotations

import argparse
import sys

# Ensure UTF-8 output on Windows (required for Rich Unicode characters)
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except AttributeError:
        pass


def cmd_init(args: argparse.Namespace) -> None:
    """Interactive first-time setup — saves API keys to ~/.sentinel/.env"""
    from pathlib import Path
    from rich.console import Console
    from rich.prompt import Prompt
    from rich.panel import Panel

    c = Console()
    c.print()
    c.print(Panel.fit(
        "[bold cyan]Welcome to SENTINEL[/bold cyan]\n"
        "[dim]Self-healing AI code quality pipeline[/dim]\n\n"
        "Let's get you set up in 2 minutes.\n"
        "Both keys below are [bold]completely free[/bold] — no credit card needed.",
        border_style="cyan",
    ))
    c.print()

    # ── Groq ──────────────────────────────────────────────────────────────────
    c.print("[bold]Step 1 of 2 — Groq API key[/bold] [dim](fast inference, free)[/dim]")
    c.print("  → Get yours at: [cyan]https://console.groq.com[/cyan]")
    c.print("  → Click [bold]API Keys[/bold] → [bold]Create API Key[/bold]")
    c.print()
    groq_key = Prompt.ask("  Paste your Groq key [dim](starts with gsk_)[/dim]").strip()
    c.print()

    # ── HuggingFace ───────────────────────────────────────────────────────────
    c.print("[bold]Step 2 of 2 — HuggingFace token[/bold] [dim](fallback when Groq quota runs out)[/dim]")
    c.print("  → Get yours at: [cyan]https://huggingface.co/settings/tokens[/cyan]")
    c.print("  → Click [bold]New token[/bold] → choose [bold]Read[/bold] → Create")
    c.print()
    hf_key = Prompt.ask("  Paste your HuggingFace token [dim](starts with hf_)[/dim]").strip()
    c.print()

    # ── Save to ~/.sentinel/.env ───────────────────────────────────────────────
    sentinel_dir = Path.home() / ".sentinel"
    sentinel_dir.mkdir(exist_ok=True)
    env_file = sentinel_dir / ".env"

    env_content = f"""# SENTINEL global config — generated by `sentinel init`
# Edit this file to change settings.
LLM_PROVIDER=cascade
GROQ_API_KEY={groq_key}
HUGGINGFACE_API_KEY={hf_key}
GROQ_MODEL_STRONG=llama-3.3-70b-versatile
GROQ_MODEL_FAST=llama-3.1-8b-instant
HF_MODEL_STRONG=Qwen/Qwen2.5-72B-Instruct
HF_MODEL_FAST=Qwen/Qwen2.5-7B-Instruct
CHROMA_PERSIST_DIR={sentinel_dir / "chroma"}
LOG_FILE={sentinel_dir / "sentinel.log"}
SANDBOX_IMAGE=sentinel-sandbox:latest
SANDBOX_TIMEOUT_SECONDS=120
SANDBOX_MEMORY_LIMIT=512m
SANDBOX_CPU_PERIOD=100000
SANDBOX_CPU_QUOTA=50000
"""
    env_file.write_text(env_content, encoding="utf-8")

    # ── Check Docker ──────────────────────────────────────────────────────────
    import subprocess
    docker_ok = subprocess.run(["docker", "info"], capture_output=True).returncode == 0

    c.print(f"[green]Config saved →[/green] [cyan]{env_file}[/cyan]")
    c.print()

    if not docker_ok:
        c.print("[yellow]Warning:[/yellow] Docker is not running.")
        c.print("  SENTINEL needs Docker for its sandbox. Install it at: [cyan]https://docker.com[/cyan]")
        c.print()

    c.print("[bold green]SENTINEL is ready![/bold green]")
    c.print()
    c.print("Run your first scan:")
    c.print("  [bold cyan]sentinel scan --path ./your-project --all[/bold cyan]")
    c.print()


def cmd_serve(args: argparse.Namespace) -> None:
    import uvicorn

    from src.api.webhook import app
    from src.core.logging import configure_logging
    from src.scheduler.maintenance import start_scheduler

    configure_logging()
    start_scheduler(repo_root=args.repo_root)
    uvicorn.run(
        app,
        host=args.host,
        port=args.port,
        log_config=None,
    )


def cmd_run(args: argparse.Namespace) -> None:
    from src.core.logging import configure_logging
    from src.core.pipeline import compile_pipeline
    from src.core.state import PRMetadata, PipelineState
    from src.integrations.git_utils import fetch_pr_diff, fetch_pr_files
    from src.integrations.github_client import GitHubClient

    configure_logging(quiet=True)

    gh = GitHubClient()
    diff = fetch_pr_diff(args.repo, args.pr)
    files = fetch_pr_files(args.repo, args.pr)
    pr_meta = gh.fetch_pr_metadata(args.repo, args.pr)
    pr_meta = pr_meta.model_copy(update={"diff": diff, "files_changed": files})

    initial_state = PipelineState(pr=pr_meta, force_review=getattr(args, "force_review", False))
    pipeline = compile_pipeline()

    from rich.console import Console
    Console().print(f"\n[bold cyan]SENTINEL[/bold cyan]  [cyan]{args.repo}#{args.pr}[/cyan]\n")
    _run_and_display(pipeline, initial_state, report_title="SENTINEL PR REPORT")


def cmd_scan(args: argparse.Namespace) -> None:
    """Run SENTINEL on local code — no GitHub PR required."""
    import re
    import subprocess
    import tarfile
    from io import BytesIO
    from pathlib import Path

    from src.core.logging import configure_logging
    from src.core.pipeline import compile_pipeline
    from src.core.state import PRMetadata, PipelineState

    configure_logging(quiet=True)

    scan_path = Path(args.path).resolve()
    if not scan_path.exists():
        print(f"Error: path '{scan_path}' does not exist.")
        sys.exit(1)

    _SKIP = (".git", "__pycache__", ".egg-info", "node_modules", ".venv", "venv", "dist", "build", ".next", "coverage", ".turbo")
    _SOURCE_EXTS = (".py", ".js", ".ts", ".jsx", ".tsx", ".mjs", ".cjs")

    def _collect_source_files(root: "Path") -> "tuple[list[str], str, int]":
        src_files: list[str] = []
        full_diff = ""
        added = 0
        for p in sorted(root.rglob("*")):
            if not p.is_file() or p.suffix not in _SOURCE_EXTS:
                continue
            rel = str(p.relative_to(root)).replace("\\", "/")
            if any(s in rel for s in _SKIP):
                continue
            src_files.append(rel)
            try:
                content = p.read_text(encoding="utf-8", errors="replace")
                lines = content.splitlines()
                added += len(lines)
                full_diff += f"\n--- /dev/null\n+++ b/{rel}\n@@ -0,0 +1,{len(lines)} @@\n"
                full_diff += "\n".join(f"+{l}" for l in lines) + "\n"
            except Exception:
                pass
        return src_files, full_diff, added

    diff = ""
    files_changed: list[str] = []
    additions = deletions = 0

    if args.all:
        print("--all flag set — scanning every source file in the path.")
        files_changed, diff, additions = _collect_source_files(scan_path)
    elif args.staged:
        diff_cmd = ["git", "diff", "--cached"]
        result = subprocess.run(diff_cmd, capture_output=True, text=True, cwd=str(scan_path), encoding="utf-8", errors="replace")
        diff = result.stdout
    elif args.branch:
        diff_cmd = ["git", "diff", args.branch]
        result = subprocess.run(diff_cmd, capture_output=True, text=True, cwd=str(scan_path), encoding="utf-8", errors="replace")
        diff = result.stdout
    else:
        result = subprocess.run(["git", "diff", "HEAD"], capture_output=True, text=True, cwd=str(scan_path), encoding="utf-8", errors="replace")
        diff = result.stdout
        if not diff.strip():
            result = subprocess.run(["git", "diff", "HEAD~1", "HEAD"], capture_output=True, text=True, cwd=str(scan_path), encoding="utf-8", errors="replace")
            diff = result.stdout

    if not args.all:
        for line in diff.splitlines():
            if line.startswith("+++ b/"):
                fp = line[6:]
                if fp and fp not in files_changed:
                    files_changed.append(fp)
            elif line.startswith("+") and not line.startswith("+++"):
                additions += 1
            elif line.startswith("-") and not line.startswith("---"):
                deletions += 1

        if not files_changed:
            print("No git diff found — falling back to full source file scan.")
            files_changed, diff, additions = _collect_source_files(scan_path)

    if not files_changed:
        print("Nothing to scan — no source files found and no git diff.")
        sys.exit(0)

    remote = subprocess.run(
        ["git", "remote", "get-url", "origin"],
        capture_output=True, text=True, cwd=str(scan_path),
    )
    repo_name = "local/scan"
    if remote.returncode == 0:
        m = re.search(r"[:/]([^/]+/[^/]+?)(?:\.git)?$", remote.stdout.strip())
        if m:
            repo_name = m.group(1)

    print(f"Packaging {scan_path.name} for sandbox…")
    buf = BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for p in sorted(scan_path.rglob("*")):
            rel = str(p.relative_to(scan_path)).replace("\\", "/")
            if any(s in rel for s in _SKIP):
                continue
            if p.is_file():
                try:
                    tar.add(str(p), arcname=rel)
                except Exception:
                    pass
    repo_archive = buf.getvalue()

    pr_meta = PRMetadata(
        repo_full_name=repo_name,
        pr_number=0,
        pr_title=f"Local scan: {scan_path.name}",
        pr_body="",
        base_branch="main",
        head_branch="local",
        head_sha="local",
        author="local",
        files_changed=files_changed,
        diff=diff,
        additions=additions,
        deletions=deletions,
    )

    initial_state = PipelineState(pr=pr_meta, repo_archive=repo_archive, force_review=getattr(args, "force_review", False))
    pipeline = compile_pipeline()

    from rich.console import Console
    from rich.table import Table
    from rich import box as rbox
    c = Console()
    c.print()
    c.print(f"[bold cyan]SENTINEL[/bold cyan]  local scan")
    info = Table.grid(padding=(0, 3))
    info.add_column(style="dim")
    info.add_column(style="cyan")
    info.add_row("Path",  str(scan_path))
    info.add_row("Repo",  repo_name)
    info.add_row("Files", str(len(files_changed)))
    info.add_row("Lines", f"+{additions}  -{deletions}")
    c.print(info)
    c.print()

    from src.cli.display import print_report, run_with_progress
    final_state = run_with_progress(pipeline, initial_state)
    print_report(final_state, title="SENTINEL LOCAL SCAN REPORT")

    if args.output:
        from pathlib import Path as _P
        _P(args.output).write_text(final_state.pr_comment or "No findings.", encoding="utf-8")
        c.print(f"[dim]Report saved →[/dim] [cyan]{args.output}[/cyan]")


def _run_and_display(pipeline, initial_state, report_title: str) -> None:
    from src.cli.display import print_report, run_with_progress
    final_state = run_with_progress(pipeline, initial_state)
    print_report(final_state, title=report_title)


def cmd_maintain(args: argparse.Namespace) -> None:
    from src.agents.self_healing import consolidation, consistency, curator, drift_checker
    from src.core.logging import configure_logging
    from src.knowledge_base.store import KnowledgeBaseStore

    configure_logging()
    kb = KnowledgeBaseStore()
    print("Running KB maintenance…")
    print("Curator:      ", curator.run(kb))
    print("Drift-Checker:", drift_checker.run(kb, args.repo_root))
    print("Consistency:  ", consistency.run(kb))
    print("Consolidation:", consolidation.run(kb))


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="sentinel",
        description="SENTINEL — self-healing AI code quality pipeline",
    )
    sub = parser.add_subparsers(dest="command")

    # init
    p_init = sub.add_parser("init", help="First-time setup — configure API keys")
    p_init.set_defaults(func=cmd_init)

    # serve
    p_serve = sub.add_parser("serve", help="Start the webhook server")
    p_serve.add_argument("--host", default="0.0.0.0")
    p_serve.add_argument("--port", type=int, default=8000)
    p_serve.add_argument("--repo-root", default=".", help="Local path to the monitored repo")
    p_serve.set_defaults(func=cmd_serve)

    # run
    p_run = sub.add_parser("run", help="Run pipeline manually on a GitHub PR")
    p_run.add_argument("--repo", required=True, help="owner/repo")
    p_run.add_argument("--pr", type=int, required=True, help="PR number")
    p_run.add_argument("--force-review", action="store_true", dest="force_review")
    p_run.set_defaults(func=cmd_run)

    # scan
    p_scan = sub.add_parser("scan", help="Scan local code — no GitHub PR required")
    p_scan.add_argument("--path", default=".", help="Directory to scan (default: current dir)")
    p_scan.add_argument("--all", action="store_true", help="Scan every source file (ignores git diff)")
    p_scan.add_argument("--staged", action="store_true", help="Scan only staged git changes")
    p_scan.add_argument("--branch", default=None, help="Diff against this branch (e.g. main)")
    p_scan.add_argument("--force-review", action="store_true", dest="force_review")
    p_scan.add_argument("--output", default=None, help="Save report to file (e.g. report.md)")
    p_scan.set_defaults(func=cmd_scan)

    # maintain
    p_maintain = sub.add_parser("maintain", help="Run KB maintenance agents manually")
    p_maintain.add_argument("--repo-root", default=".", help="Local path to the monitored repo")
    p_maintain.set_defaults(func=cmd_maintain)

    args = parser.parse_args()
    if not hasattr(args, "func"):
        parser.print_help()
        sys.exit(1)
    args.func(args)


if __name__ == "__main__":
    main()
